stages:
- build


docker-build:
  image: docker:latest
  stage: build
  services:
  - docker:dind
  before_script:
  - echo $CI_BUILD_TOKEN | docker login -u "$DOCKERHUB_USER" -p "$DOCKERHUB_TOKEN"
    https://index.docker.io/v1/
  script:
  - ls .
  - docker build -t fiddler110/mtg-dungeon:latest .
  - docker push fiddler110/mtg-dungeon:latest
